#!/bin/bash

trap ctrl_c SIGINT

function ctrl_c {
  make --no-print-directory clean && \
    echo -e "\033[1;92mPatch cleaned\033[0m" || \
    echo -e "\033[1;33mCould not clean patch\033[0m"
  exit $?
}

function watch_inotify {
  inotifywait --recursive \
    --event modify,move,create,delete \
    $DIRECTORY_TO_OBSERVE
}

function watch_fswatch {
  fswatch --recursive --one-event \
    --event Created --event Updated --event Removed \
    ${DIRECTORY_TO_OBSERVE}
}


if command -v inotifywait > /dev/null 2>&1; then
  whichWatcher=inotify
  function watcher { watch_inotify; }
elif command -v fswatch > /dev/null 2>&1; then
  whichWatcher=fswatch
  function watcher { watch_fswatch; }
else
  echo -e "\033[1;31m[ERROR] No watcher available\033[0m"
  echo "Neither 'inotify' nor 'fswatch' are available."
  echo "You can follow 'CONTRIBUTING.md' guidelines to install one of them,"
  echo ""
  echo -e "\033[1;33m[alternative]\033[0m follow these steps:"
  echo "1. run 'make set-override' first,"
  echo "2. then 'make patch' every time you change a file in 'srcd' dir"
  echo "3. and 'make clean' once you finish developing"
  echo ""
  exit 1
fi

make --no-print-directory apply-patch
echo -e "\033[1;92mWatching for changes in 'srcd'; using '${whichWatcher}' ...\033[0m"
while watcher; do
  make --no-print-directory apply-patch
done
